/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c0c7ce",
        "secondary-container": "#dce3eb",
        "surface-container-low": "#f6f3ed",
        "surface": "#fcf9f3",
        "on-tertiary-container": "#a4bfff",
        "on-tertiary-fixed": "#001944",
        "secondary-fixed": "#dce3eb",
        "outline-variant": "#e3beb9",
        "on-background": "#1c1c18",
        "secondary": "#585f65",
        "inverse-primary": "#ffb4aa",
        "surface-tint": "#b7221d",
        "outline": "#8f706c",
        "tertiary-fixed": "#d9e2ff",
        "surface-variant": "#e5e2dc",
        "surface-container": "#f0eee8",
        "primary": "#750005",
        "background": "#fcf9f3",
        "tertiary-fixed-dim": "#afc6ff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-dim": "#dcdad4",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004299",
        "surface-bright": "#fcf9f3",
        "on-primary-fixed": "#410001",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe8e2",
        "on-secondary-container": "#5e656b",
        "error": "#ba1a1a",
        "surface-container-highest": "#e5e2dc",
        "on-surface-variant": "#5b403d",
        "on-surface": "#1c1c18",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#930008",
        "primary-fixed": "#ffdad5",
        "primary-container": "#9e0b0e",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#31312d",
        "tertiary": "#00337a",
        "on-secondary-fixed": "#161c22",
        "tertiary-container": "#0049a7",
        "on-secondary-fixed-variant": "#41484e",
        "inverse-on-surface": "#f3f0ea",
        "primary-fixed-dim": "#ffb4aa",
        "on-primary-container": "#ffa99e"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
